/* @flow */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateMastersInput = {|
  type: MasterType,
  masterCode: string,
  party?: ?PartyInput,
  product?: ?ProductInput,
  svb?: ?SVBInput,
|};

export type MasterType =
  "PARTY" |
  "SVB" |
  "PRODUCT";


export type PartyInput = {|
  partyCode: string,
  partyName: string,
  partyType?: ?number,
  validPartyRoles?: ?Array< ?PartyRole >,
  organizationType?: ?string,
  iecCode?: ?string,
  branchSrno?: ?string,
  address?: ?string,
  city?: ?string,
  state?: ?string,
  pincode?: ?string,
  country?: ?string,
|};

export type PartyRole =
  "IMPORTER" |
  "EXPORTER" |
  "CHA" |
  "BROKER" |
  "SVB" |
  "SUPPLIER";


export type ProductInput = {|
  hsn?: ?HSNInput,
  partDescription?: ?string,
  supplier?: ?PartyInput,
  partType?: ?number,
  shipper?: ?PartyInput,
  customer?: ?PartyInput,
  eximSchemeCode?: ?string,
  customsUom?: ?number,
  genericDescription?: ?string,
  manufacturer?: ?PartyInput,
  brand?: ?string,
  model?: ?string,
  enduse?: ?string,
  originCountry?: ?number,
  countryOfSource?: ?number,
  countryOfTansit?: ?number,
|};

export type HSNInput = {|
  hsncode: number,
  hsnDescription?: ?string,
  uomId?: ?number,
  countryid?: ?number,
  totChargeValue?: ?number,
  effectiveStartdate?: ?any,
  effectiveEnddate?: ?any,
  status?: ?number,
  policy?: ?string,
  casRegistryNumber?: ?string,
  remarks?: ?string,
  products?: ?Array< ?ProductInput >,
  hsnDuties?: ?Array< ?string >,
  notidtl?: ?string,
  pga?: ?string,
|};

export type SVBInput = {|
  Company?: ?PartyInput,
  shipper?: ?PartyInput,
  relation: string,
  svbRefNo?: ?string,
  svbDate?: ?any,
  svbValidUpto?: ?any,
  customsOffice?: ?string,
  tobeLoadedon?: ?string,
  loadingRateassval?: ?string,
  assblStatus?: ?number,
  loadingDutyrate?: ?number,
  loadingDutyratecur?: ?number,
  dutyStatus?: ?number,
|};

export type ModelMastersConditionInput = {|
  and?: ?Array< ?ModelMastersConditionInput >,
  or?: ?Array< ?ModelMastersConditionInput >,
  not?: ?ModelMastersConditionInput,
|};

export type UpdateMastersInput = {|
  type: MasterType,
  masterCode: string,
  party?: ?PartyInput,
  product?: ?ProductInput,
  svb?: ?SVBInput,
|};

export type DeleteMastersInput = {|
  type: MasterType,
  masterCode: string,
|};

export type ModelStringKeyConditionInput = {|
  eq?: ?string,
  le?: ?string,
  lt?: ?string,
  ge?: ?string,
  gt?: ?string,
  between?: ?Array< ?string >,
  beginsWith?: ?string,
|};

export type ModelMastersFilterInput = {|
  type?: ?ModelMasterTypeInput,
  masterCode?: ?ModelStringInput,
  and?: ?Array< ?ModelMastersFilterInput >,
  or?: ?Array< ?ModelMastersFilterInput >,
  not?: ?ModelMastersFilterInput,
|};

export type ModelMasterTypeInput = {|
  eq?: ?MasterType,
  ne?: ?MasterType,
|};

export type ModelStringInput = {|
  ne?: ?string,
  eq?: ?string,
  le?: ?string,
  lt?: ?string,
  ge?: ?string,
  gt?: ?string,
  contains?: ?string,
  notContains?: ?string,
  between?: ?Array< ?string >,
  beginsWith?: ?string,
  attributeExists?: ?boolean,
  attributeType?: ?ModelAttributeTypes,
  size?: ?ModelSizeInput,
|};

export type ModelAttributeTypes =
  "binary" |
  "binarySet" |
  "bool" |
  "list" |
  "map" |
  "number" |
  "numberSet" |
  "string" |
  "stringSet" |
  "_null";


export type ModelSizeInput = {|
  ne?: ?number,
  eq?: ?number,
  le?: ?number,
  lt?: ?number,
  ge?: ?number,
  gt?: ?number,
  between?: ?Array< ?number >,
|};

export type ModelSortDirection =
  "ASC" |
  "DESC";


export type CreateMastersMutationVariables = {|
  input: CreateMastersInput,
  condition?: ?ModelMastersConditionInput,
|};

export type CreateMastersMutation = {|
  createMasters: ? {|
    __typename: "Masters",
    type: MasterType,
    masterCode: string,
    party: ? {|
      __typename: "Party",
      partyCode: string,
      partyName: string,
      partyType: ?number,
      validPartyRoles: ?Array< ?PartyRole >,
      organizationType: ?string,
      iecCode: ?string,
      branchSrno: ?string,
      address: ?string,
      city: ?string,
      state: ?string,
      pincode: ?string,
      country: ?string,
    |},
    product: ? {|
      __typename: "Product",
      hsn: ? {|
        __typename: "HSN",
        hsncode: number,
        hsnDescription: ?string,
        uomId: ?number,
        countryid: ?number,
        totChargeValue: ?number,
        effectiveStartdate: ?any,
        effectiveEnddate: ?any,
        status: ?number,
        policy: ?string,
        casRegistryNumber: ?string,
        remarks: ?string,
        hsnDuties: ?Array< ?string >,
        notidtl: ?string,
        pga: ?string,
      |},
      partDescription: ?string,
      supplier: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      partType: ?number,
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      customer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      eximSchemeCode: ?string,
      customsUom: ?number,
      genericDescription: ?string,
      manufacturer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      brand: ?string,
      model: ?string,
      enduse: ?string,
      originCountry: ?number,
      countryOfSource: ?number,
      countryOfTansit: ?number,
    |},
    svb: ? {|
      __typename: "SVB",
      Company: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      relation: string,
      svbRefNo: ?string,
      svbDate: ?any,
      svbValidUpto: ?any,
      customsOffice: ?string,
      tobeLoadedon: ?string,
      loadingRateassval: ?string,
      assblStatus: ?number,
      loadingDutyrate: ?number,
      loadingDutyratecur: ?number,
      dutyStatus: ?number,
    |},
    createdAt: any,
    updatedAt: any,
  |},
|};

export type UpdateMastersMutationVariables = {|
  input: UpdateMastersInput,
  condition?: ?ModelMastersConditionInput,
|};

export type UpdateMastersMutation = {|
  updateMasters: ? {|
    __typename: "Masters",
    type: MasterType,
    masterCode: string,
    party: ? {|
      __typename: "Party",
      partyCode: string,
      partyName: string,
      partyType: ?number,
      validPartyRoles: ?Array< ?PartyRole >,
      organizationType: ?string,
      iecCode: ?string,
      branchSrno: ?string,
      address: ?string,
      city: ?string,
      state: ?string,
      pincode: ?string,
      country: ?string,
    |},
    product: ? {|
      __typename: "Product",
      hsn: ? {|
        __typename: "HSN",
        hsncode: number,
        hsnDescription: ?string,
        uomId: ?number,
        countryid: ?number,
        totChargeValue: ?number,
        effectiveStartdate: ?any,
        effectiveEnddate: ?any,
        status: ?number,
        policy: ?string,
        casRegistryNumber: ?string,
        remarks: ?string,
        hsnDuties: ?Array< ?string >,
        notidtl: ?string,
        pga: ?string,
      |},
      partDescription: ?string,
      supplier: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      partType: ?number,
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      customer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      eximSchemeCode: ?string,
      customsUom: ?number,
      genericDescription: ?string,
      manufacturer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      brand: ?string,
      model: ?string,
      enduse: ?string,
      originCountry: ?number,
      countryOfSource: ?number,
      countryOfTansit: ?number,
    |},
    svb: ? {|
      __typename: "SVB",
      Company: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      relation: string,
      svbRefNo: ?string,
      svbDate: ?any,
      svbValidUpto: ?any,
      customsOffice: ?string,
      tobeLoadedon: ?string,
      loadingRateassval: ?string,
      assblStatus: ?number,
      loadingDutyrate: ?number,
      loadingDutyratecur: ?number,
      dutyStatus: ?number,
    |},
    createdAt: any,
    updatedAt: any,
  |},
|};

export type DeleteMastersMutationVariables = {|
  input: DeleteMastersInput,
  condition?: ?ModelMastersConditionInput,
|};

export type DeleteMastersMutation = {|
  deleteMasters: ? {|
    __typename: "Masters",
    type: MasterType,
    masterCode: string,
    party: ? {|
      __typename: "Party",
      partyCode: string,
      partyName: string,
      partyType: ?number,
      validPartyRoles: ?Array< ?PartyRole >,
      organizationType: ?string,
      iecCode: ?string,
      branchSrno: ?string,
      address: ?string,
      city: ?string,
      state: ?string,
      pincode: ?string,
      country: ?string,
    |},
    product: ? {|
      __typename: "Product",
      hsn: ? {|
        __typename: "HSN",
        hsncode: number,
        hsnDescription: ?string,
        uomId: ?number,
        countryid: ?number,
        totChargeValue: ?number,
        effectiveStartdate: ?any,
        effectiveEnddate: ?any,
        status: ?number,
        policy: ?string,
        casRegistryNumber: ?string,
        remarks: ?string,
        hsnDuties: ?Array< ?string >,
        notidtl: ?string,
        pga: ?string,
      |},
      partDescription: ?string,
      supplier: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      partType: ?number,
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      customer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      eximSchemeCode: ?string,
      customsUom: ?number,
      genericDescription: ?string,
      manufacturer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      brand: ?string,
      model: ?string,
      enduse: ?string,
      originCountry: ?number,
      countryOfSource: ?number,
      countryOfTansit: ?number,
    |},
    svb: ? {|
      __typename: "SVB",
      Company: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      relation: string,
      svbRefNo: ?string,
      svbDate: ?any,
      svbValidUpto: ?any,
      customsOffice: ?string,
      tobeLoadedon: ?string,
      loadingRateassval: ?string,
      assblStatus: ?number,
      loadingDutyrate: ?number,
      loadingDutyratecur: ?number,
      dutyStatus: ?number,
    |},
    createdAt: any,
    updatedAt: any,
  |},
|};

export type GetMastersQueryVariables = {|
  type: MasterType,
  masterCode: string,
|};

export type GetMastersQuery = {|
  getMasters: ? {|
    __typename: "Masters",
    type: MasterType,
    masterCode: string,
    party: ? {|
      __typename: "Party",
      partyCode: string,
      partyName: string,
      partyType: ?number,
      validPartyRoles: ?Array< ?PartyRole >,
      organizationType: ?string,
      iecCode: ?string,
      branchSrno: ?string,
      address: ?string,
      city: ?string,
      state: ?string,
      pincode: ?string,
      country: ?string,
    |},
    product: ? {|
      __typename: "Product",
      hsn: ? {|
        __typename: "HSN",
        hsncode: number,
        hsnDescription: ?string,
        uomId: ?number,
        countryid: ?number,
        totChargeValue: ?number,
        effectiveStartdate: ?any,
        effectiveEnddate: ?any,
        status: ?number,
        policy: ?string,
        casRegistryNumber: ?string,
        remarks: ?string,
        hsnDuties: ?Array< ?string >,
        notidtl: ?string,
        pga: ?string,
      |},
      partDescription: ?string,
      supplier: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      partType: ?number,
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      customer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      eximSchemeCode: ?string,
      customsUom: ?number,
      genericDescription: ?string,
      manufacturer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      brand: ?string,
      model: ?string,
      enduse: ?string,
      originCountry: ?number,
      countryOfSource: ?number,
      countryOfTansit: ?number,
    |},
    svb: ? {|
      __typename: "SVB",
      Company: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      relation: string,
      svbRefNo: ?string,
      svbDate: ?any,
      svbValidUpto: ?any,
      customsOffice: ?string,
      tobeLoadedon: ?string,
      loadingRateassval: ?string,
      assblStatus: ?number,
      loadingDutyrate: ?number,
      loadingDutyratecur: ?number,
      dutyStatus: ?number,
    |},
    createdAt: any,
    updatedAt: any,
  |},
|};

export type ListMasterssQueryVariables = {|
  type?: ?MasterType,
  masterCode?: ?ModelStringKeyConditionInput,
  filter?: ?ModelMastersFilterInput,
  limit?: ?number,
  nextToken?: ?string,
  sortDirection?: ?ModelSortDirection,
|};

export type ListMasterssQuery = {|
  listMasterss: ? {|
    __typename: "ModelMastersConnection",
    items: ? Array<? {|
      __typename: "Masters",
      type: MasterType,
      masterCode: string,
      party: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      product: ? {|
        __typename: "Product",
        partDescription: ?string,
        partType: ?number,
        eximSchemeCode: ?string,
        customsUom: ?number,
        genericDescription: ?string,
        brand: ?string,
        model: ?string,
        enduse: ?string,
        originCountry: ?number,
        countryOfSource: ?number,
        countryOfTansit: ?number,
      |},
      svb: ? {|
        __typename: "SVB",
        relation: string,
        svbRefNo: ?string,
        svbDate: ?any,
        svbValidUpto: ?any,
        customsOffice: ?string,
        tobeLoadedon: ?string,
        loadingRateassval: ?string,
        assblStatus: ?number,
        loadingDutyrate: ?number,
        loadingDutyratecur: ?number,
        dutyStatus: ?number,
      |},
      createdAt: any,
      updatedAt: any,
    |} >,
    nextToken: ?string,
  |},
|};

export type OnCreateMastersSubscription = {|
  onCreateMasters: ? {|
    __typename: "Masters",
    type: MasterType,
    masterCode: string,
    party: ? {|
      __typename: "Party",
      partyCode: string,
      partyName: string,
      partyType: ?number,
      validPartyRoles: ?Array< ?PartyRole >,
      organizationType: ?string,
      iecCode: ?string,
      branchSrno: ?string,
      address: ?string,
      city: ?string,
      state: ?string,
      pincode: ?string,
      country: ?string,
    |},
    product: ? {|
      __typename: "Product",
      hsn: ? {|
        __typename: "HSN",
        hsncode: number,
        hsnDescription: ?string,
        uomId: ?number,
        countryid: ?number,
        totChargeValue: ?number,
        effectiveStartdate: ?any,
        effectiveEnddate: ?any,
        status: ?number,
        policy: ?string,
        casRegistryNumber: ?string,
        remarks: ?string,
        hsnDuties: ?Array< ?string >,
        notidtl: ?string,
        pga: ?string,
      |},
      partDescription: ?string,
      supplier: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      partType: ?number,
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      customer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      eximSchemeCode: ?string,
      customsUom: ?number,
      genericDescription: ?string,
      manufacturer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      brand: ?string,
      model: ?string,
      enduse: ?string,
      originCountry: ?number,
      countryOfSource: ?number,
      countryOfTansit: ?number,
    |},
    svb: ? {|
      __typename: "SVB",
      Company: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      relation: string,
      svbRefNo: ?string,
      svbDate: ?any,
      svbValidUpto: ?any,
      customsOffice: ?string,
      tobeLoadedon: ?string,
      loadingRateassval: ?string,
      assblStatus: ?number,
      loadingDutyrate: ?number,
      loadingDutyratecur: ?number,
      dutyStatus: ?number,
    |},
    createdAt: any,
    updatedAt: any,
  |},
|};

export type OnUpdateMastersSubscription = {|
  onUpdateMasters: ? {|
    __typename: "Masters",
    type: MasterType,
    masterCode: string,
    party: ? {|
      __typename: "Party",
      partyCode: string,
      partyName: string,
      partyType: ?number,
      validPartyRoles: ?Array< ?PartyRole >,
      organizationType: ?string,
      iecCode: ?string,
      branchSrno: ?string,
      address: ?string,
      city: ?string,
      state: ?string,
      pincode: ?string,
      country: ?string,
    |},
    product: ? {|
      __typename: "Product",
      hsn: ? {|
        __typename: "HSN",
        hsncode: number,
        hsnDescription: ?string,
        uomId: ?number,
        countryid: ?number,
        totChargeValue: ?number,
        effectiveStartdate: ?any,
        effectiveEnddate: ?any,
        status: ?number,
        policy: ?string,
        casRegistryNumber: ?string,
        remarks: ?string,
        hsnDuties: ?Array< ?string >,
        notidtl: ?string,
        pga: ?string,
      |},
      partDescription: ?string,
      supplier: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      partType: ?number,
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      customer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      eximSchemeCode: ?string,
      customsUom: ?number,
      genericDescription: ?string,
      manufacturer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      brand: ?string,
      model: ?string,
      enduse: ?string,
      originCountry: ?number,
      countryOfSource: ?number,
      countryOfTansit: ?number,
    |},
    svb: ? {|
      __typename: "SVB",
      Company: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      relation: string,
      svbRefNo: ?string,
      svbDate: ?any,
      svbValidUpto: ?any,
      customsOffice: ?string,
      tobeLoadedon: ?string,
      loadingRateassval: ?string,
      assblStatus: ?number,
      loadingDutyrate: ?number,
      loadingDutyratecur: ?number,
      dutyStatus: ?number,
    |},
    createdAt: any,
    updatedAt: any,
  |},
|};

export type OnDeleteMastersSubscription = {|
  onDeleteMasters: ? {|
    __typename: "Masters",
    type: MasterType,
    masterCode: string,
    party: ? {|
      __typename: "Party",
      partyCode: string,
      partyName: string,
      partyType: ?number,
      validPartyRoles: ?Array< ?PartyRole >,
      organizationType: ?string,
      iecCode: ?string,
      branchSrno: ?string,
      address: ?string,
      city: ?string,
      state: ?string,
      pincode: ?string,
      country: ?string,
    |},
    product: ? {|
      __typename: "Product",
      hsn: ? {|
        __typename: "HSN",
        hsncode: number,
        hsnDescription: ?string,
        uomId: ?number,
        countryid: ?number,
        totChargeValue: ?number,
        effectiveStartdate: ?any,
        effectiveEnddate: ?any,
        status: ?number,
        policy: ?string,
        casRegistryNumber: ?string,
        remarks: ?string,
        hsnDuties: ?Array< ?string >,
        notidtl: ?string,
        pga: ?string,
      |},
      partDescription: ?string,
      supplier: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      partType: ?number,
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      customer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      eximSchemeCode: ?string,
      customsUom: ?number,
      genericDescription: ?string,
      manufacturer: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      brand: ?string,
      model: ?string,
      enduse: ?string,
      originCountry: ?number,
      countryOfSource: ?number,
      countryOfTansit: ?number,
    |},
    svb: ? {|
      __typename: "SVB",
      Company: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      shipper: ? {|
        __typename: "Party",
        partyCode: string,
        partyName: string,
        partyType: ?number,
        validPartyRoles: ?Array< ?PartyRole >,
        organizationType: ?string,
        iecCode: ?string,
        branchSrno: ?string,
        address: ?string,
        city: ?string,
        state: ?string,
        pincode: ?string,
        country: ?string,
      |},
      relation: string,
      svbRefNo: ?string,
      svbDate: ?any,
      svbValidUpto: ?any,
      customsOffice: ?string,
      tobeLoadedon: ?string,
      loadingRateassval: ?string,
      assblStatus: ?number,
      loadingDutyrate: ?number,
      loadingDutyratecur: ?number,
      dutyStatus: ?number,
    |},
    createdAt: any,
    updatedAt: any,
  |},
|};