// @flow
// this is an auto generated file. This will be overwritten

export const onCreateMasters = /* GraphQL */ `
  subscription OnCreateMasters {
    onCreateMasters {
      type
      masterCode
      party {
        partyCode
        partyName
        partyType
        validPartyRoles
        organizationType
        iecCode
        branchSrno
        address
        city
        state
        pincode
        country
      }
      product {
        hsn {
          hsncode
          hsnDescription
          uomId
          countryid
          totChargeValue
          effectiveStartdate
          effectiveEnddate
          status
          policy
          casRegistryNumber
          remarks
          hsnDuties
          notidtl
          pga
        }
        partDescription
        supplier {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        partType
        shipper {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        customer {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        eximSchemeCode
        customsUom
        genericDescription
        manufacturer {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        brand
        model
        enduse
        originCountry
        countryOfSource
        countryOfTansit
      }
      svb {
        Company {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        shipper {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        relation
        svbRefNo
        svbDate
        svbValidUpto
        customsOffice
        tobeLoadedon
        loadingRateassval
        assblStatus
        loadingDutyrate
        loadingDutyratecur
        dutyStatus
      }
      createdAt
      updatedAt
    }
  }
`;
export const onUpdateMasters = /* GraphQL */ `
  subscription OnUpdateMasters {
    onUpdateMasters {
      type
      masterCode
      party {
        partyCode
        partyName
        partyType
        validPartyRoles
        organizationType
        iecCode
        branchSrno
        address
        city
        state
        pincode
        country
      }
      product {
        hsn {
          hsncode
          hsnDescription
          uomId
          countryid
          totChargeValue
          effectiveStartdate
          effectiveEnddate
          status
          policy
          casRegistryNumber
          remarks
          hsnDuties
          notidtl
          pga
        }
        partDescription
        supplier {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        partType
        shipper {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        customer {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        eximSchemeCode
        customsUom
        genericDescription
        manufacturer {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        brand
        model
        enduse
        originCountry
        countryOfSource
        countryOfTansit
      }
      svb {
        Company {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        shipper {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        relation
        svbRefNo
        svbDate
        svbValidUpto
        customsOffice
        tobeLoadedon
        loadingRateassval
        assblStatus
        loadingDutyrate
        loadingDutyratecur
        dutyStatus
      }
      createdAt
      updatedAt
    }
  }
`;
export const onDeleteMasters = /* GraphQL */ `
  subscription OnDeleteMasters {
    onDeleteMasters {
      type
      masterCode
      party {
        partyCode
        partyName
        partyType
        validPartyRoles
        organizationType
        iecCode
        branchSrno
        address
        city
        state
        pincode
        country
      }
      product {
        hsn {
          hsncode
          hsnDescription
          uomId
          countryid
          totChargeValue
          effectiveStartdate
          effectiveEnddate
          status
          policy
          casRegistryNumber
          remarks
          hsnDuties
          notidtl
          pga
        }
        partDescription
        supplier {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        partType
        shipper {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        customer {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        eximSchemeCode
        customsUom
        genericDescription
        manufacturer {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        brand
        model
        enduse
        originCountry
        countryOfSource
        countryOfTansit
      }
      svb {
        Company {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        shipper {
          partyCode
          partyName
          partyType
          validPartyRoles
          organizationType
          iecCode
          branchSrno
          address
          city
          state
          pincode
          country
        }
        relation
        svbRefNo
        svbDate
        svbValidUpto
        customsOffice
        tobeLoadedon
        loadingRateassval
        assblStatus
        loadingDutyrate
        loadingDutyratecur
        dutyStatus
      }
      createdAt
      updatedAt
    }
  }
`;
